"""Generate a pinned requirements.lock from the currently installed environment.

Resolves the transitive closure of the project's runtime dependencies (declared in
pyproject.toml) and pins each to the version installed in the active interpreter, so
deployments can reproduce the exact tested dependency set with `pip install -r`.
"""

from __future__ import annotations

import sys
import tomllib
from importlib import metadata
from pathlib import Path

from packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parents[1]


def _top_level_names() -> list[str]:
    with (ROOT / "pyproject.toml").open("rb") as handle:
        data = tomllib.load(handle)
    names: list[str] = []
    for spec in data["project"]["dependencies"]:
        names.append(Requirement(spec).name)
    return names


def _closure(seed: list[str]) -> dict[str, str]:
    resolved: dict[str, str] = {}
    stack = list(seed)
    while stack:
        raw = stack.pop()
        name = Requirement(raw).name if any(c in raw for c in "<>=!~[ ") else raw
        try:
            dist = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            continue
        canonical = dist.metadata["Name"]
        if canonical.lower() in resolved:
            continue
        resolved[canonical.lower()] = f"{canonical}=={dist.version}"
        for req_str in dist.requires or []:
            requirement = Requirement(req_str)
            if requirement.marker and not requirement.marker.evaluate():
                # Skip deps that do not apply to this interpreter/platform/extra.
                continue
            stack.append(requirement.name)
    return resolved


def main() -> None:
    resolved = _closure(_top_level_names())
    lines = [
        "# Auto-generated by scripts/generate_lock.py — do not edit by hand.",
        f"# Locked from Python {sys.version.split()[0]} on the tested environment.",
        "# Regenerate with: python -m scripts.generate_lock",
        "",
    ]
    lines += [resolved[key] for key in sorted(resolved)]
    (ROOT / "requirements.lock").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote requirements.lock with {len(resolved)} pinned packages.")


if __name__ == "__main__":
    main()
